name: My First CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "learning yml step by step"
      - name: main
        uses: actions/checkout@v6
      - name: list files
        run: ls
